### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [AlexanderGurnet/AlexanderGurnet.github.io#3]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`denis_zlocate@abstract.com` - символ подчерка ( `_` ) является разрешенным для части содержащей имя пользователя (до @) 
`some-extra-long-name@some.extra.long.domain.name` - адрес почты может включать в себя произвольное число поддоменов.

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`my---mail@site.ru` - адрес почты содержащий несколько спецсимволов подряд является некорректным

### Номер телефона
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`https://some.amazing.site.name.academy.some` - адрес сайта может содержать произвольное число поддоменов

**Можно лучше** следующие некорректные кейсы проходят валидацию
http://www.google.ru/////// - в пути количество слешей подряд должно быть ограничено 1

**Comment by AlexanderGurnet** [comment]
Спасибо за ревью, исправил указанные замечания

**Comment by zlocate** [comment]
Добрый день. Благодарю вас за оперативное внесение изменений и тщательную проработку тест-кейсов, а также комментариев "можно лучше.
Работа принята. Желаю успехов в дальнейшем прохождении курса.

**Comment by AlexanderGurnet** [comment]
Спасибо большое, вам тоже желаю успехов!
